//! Generates the Bash/Readline integration.
//!
//! Bash does not expose an equivalent to Zsh's `POSTDISPLAY`, so this adapter
//! uses `bind -x` handlers and a small ANSI suggestion block below the prompt.

use crate::config::Config;
use std::env;

const PRINTABLE_ASCII: std::ops::RangeInclusive<u8> = 0x20..=0x7e;

pub fn generate(config: &Config) -> String {
    let executable = env::current_exe()
        .ok()
        .and_then(|path| path.to_str().map(str::to_owned))
        .unwrap_or_else(|| "rrsreadline".to_owned());
    let mut output = BASE_SCRIPT
        .replace("__RRSREADLINE_BIN__", &shell_single_quote(&executable))
        .replace("__RRSREADLINE_SLOTS__", &config.max_suggestions.to_string());
    output.push_str(static_bindings());
    output.push_str(&character_bindings());
    output.push_str(
        "\ntrap __rrsreadline_preexec DEBUG\nPROMPT_COMMAND=\"__rrsreadline_prompt_reset${PROMPT_COMMAND:+; }$PROMPT_COMMAND\"\n",
    );
    output
}

const BASE_SCRIPT: &str = r#"# Generated by `rrsreadline init bash`.
# Source this output from `.bashrc` with: eval "$(rrsreadline init bash)"
_RRSREADLINE_BIN=__RRSREADLINE_BIN__
_RRSREADLINE_SLOTS=__RRSREADLINE_SLOTS__
_RRSREADLINE_QUERY=""
_RRSREADLINE_SELECTED=-1
_RRSREADLINE_PREDICTIONS_HIDDEN=0
_RRSREADLINE_BUSY=0
_RRSREADLINE_SUGGESTIONS=()
_RRSREADLINE_HISTORY=()
_RRSREADLINE_HISTORY_QUERY=""
_RRSREADLINE_HISTORY_INDEX=-1

__rrsreadline_load() {
    local item
    _RRSREADLINE_SUGGESTIONS=()
    if [[ -n "$_RRSREADLINE_QUERY" ]]; then
        while IFS= read -r item; do
            [[ -n "$item" ]] && _RRSREADLINE_SUGGESTIONS[${#_RRSREADLINE_SUGGESTIONS[@]}]="$item"
        done < <("$_RRSREADLINE_BIN" suggest --shell bash "$_RRSREADLINE_QUERY")
    fi
}

__rrsreadline_draw() {
    local i line
    printf '%s' $'\e7'
    for ((i = 0; i < _RRSREADLINE_SLOTS; i++)); do
        printf '%s' $'\e[1B\e[2K\r'
        if (( i < ${#_RRSREADLINE_SUGGESTIONS[@]} )); then
            line="  ${_RRSREADLINE_SUGGESTIONS[i]}"
            if (( i == _RRSREADLINE_SELECTED )); then
                line="❯ ${_RRSREADLINE_SUGGESTIONS[i]}"
            fi
            printf '%s' "$line"
        fi
    done
    printf '%s' $'\e8'
}

__rrsreadline_clear() {
    local i
    printf '%s' $'\e7'
    for ((i = 0; i < _RRSREADLINE_SLOTS; i++)); do
        printf '%s' $'\e[1B\e[2K\r'
    done
    printf '%s' $'\e8'
}

__rrsreadline_load_history() {
    local line
    _RRSREADLINE_HISTORY=()
    while IFS= read -r line; do
        [[ -n "$line" && "$line" != \#* ]] || continue
        _RRSREADLINE_HISTORY[${#_RRSREADLINE_HISTORY[@]}]="$line"
    done < "${HISTFILE:-$HOME/.bash_history}"
}

__rrsreadline_native_history() {
    local direction="$1" i start found=-1
    if (( _RRSREADLINE_HISTORY_INDEX < 0 )); then
        _RRSREADLINE_HISTORY_QUERY="$READLINE_LINE"
        __rrsreadline_load_history
    fi
    if [[ "$direction" == up ]]; then
        start=$(( ${#_RRSREADLINE_HISTORY[@]} - 1 ))
        (( _RRSREADLINE_HISTORY_INDEX >= 0 )) && start=$(( _RRSREADLINE_HISTORY_INDEX - 1 ))
        for ((i = start; i >= 0; i--)); do
            if [[ "${_RRSREADLINE_HISTORY[i]}" == "$_RRSREADLINE_HISTORY_QUERY"* ]]; then
                found=$i
                break
            fi
        done
    else
        start=0
        (( _RRSREADLINE_HISTORY_INDEX >= 0 )) && start=$(( _RRSREADLINE_HISTORY_INDEX + 1 ))
        for ((i = start; i < ${#_RRSREADLINE_HISTORY[@]}; i++)); do
            if [[ "${_RRSREADLINE_HISTORY[i]}" == "$_RRSREADLINE_HISTORY_QUERY"* ]]; then
                found=$i
                break
            fi
        done
    fi
    if (( found >= 0 )); then
        _RRSREADLINE_HISTORY_INDEX=$found
        READLINE_LINE="${_RRSREADLINE_HISTORY[found]}"
        READLINE_POINT=${#READLINE_LINE}
    fi
}

__rrsreadline_update() {
    local direction="$1"
    local show_predictions="${2:-1}"
    if [[ "$direction" == none ]]; then
        _RRSREADLINE_QUERY="${READLINE_LINE:0:READLINE_POINT}"
        _RRSREADLINE_SELECTED=-1
        _RRSREADLINE_HISTORY_QUERY="$READLINE_LINE"
        _RRSREADLINE_HISTORY_INDEX=-1
    fi

    if [[ "$show_predictions" == 1 ]]; then
        _RRSREADLINE_PREDICTIONS_HIDDEN=0
    fi

    if (( _RRSREADLINE_PREDICTIONS_HIDDEN )); then
        _RRSREADLINE_SUGGESTIONS=()
        _RRSREADLINE_SELECTED=-1
        __rrsreadline_clear
        if [[ "$direction" == up || "$direction" == down ]]; then
            __rrsreadline_native_history "$direction"
        fi
        return
    fi

    __rrsreadline_load
    if (( ${#_RRSREADLINE_SUGGESTIONS[@]} == 0 )); then
        _RRSREADLINE_SELECTED=-1
    elif [[ "$direction" == down ]]; then
        if (( _RRSREADLINE_SELECTED < 0 )); then
            _RRSREADLINE_SELECTED=0
        else
            _RRSREADLINE_SELECTED=$(( (_RRSREADLINE_SELECTED + 1) % ${#_RRSREADLINE_SUGGESTIONS[@]} ))
        fi
    elif [[ "$direction" == up ]]; then
        if (( _RRSREADLINE_SELECTED < 0 )); then
            _RRSREADLINE_SELECTED=$(( ${#_RRSREADLINE_SUGGESTIONS[@]} - 1 ))
        else
            _RRSREADLINE_SELECTED=$(( (_RRSREADLINE_SELECTED - 1 + ${#_RRSREADLINE_SUGGESTIONS[@]}) % ${#_RRSREADLINE_SUGGESTIONS[@]} ))
        fi
    fi

    if (( _RRSREADLINE_SELECTED >= 0 )); then
        READLINE_LINE="${_RRSREADLINE_SUGGESTIONS[_RRSREADLINE_SELECTED]}"
        READLINE_POINT=${#READLINE_LINE}
    fi
    if (( ${#_RRSREADLINE_SUGGESTIONS[@]} == 0 )) && [[ "$direction" == up || "$direction" == down ]]; then
        __rrsreadline_native_history "$direction"
    fi
    __rrsreadline_draw
}

__rrsreadline_insert() {
    _RRSREADLINE_BUSY=1
    local character="$1"
    if (( _RRSREADLINE_SELECTED >= 0 || _RRSREADLINE_HISTORY_INDEX >= 0 )); then
        READLINE_LINE="$_RRSREADLINE_QUERY"
        READLINE_POINT=${#READLINE_LINE}
    fi
    READLINE_LINE="${READLINE_LINE:0:READLINE_POINT}${character}${READLINE_LINE:READLINE_POINT}"
    READLINE_POINT=$(( READLINE_POINT + 1 ))
    __rrsreadline_update none
    _RRSREADLINE_BUSY=0
}

__rrsreadline_backspace() {
    _RRSREADLINE_BUSY=1
    if (( _RRSREADLINE_SELECTED >= 0 || _RRSREADLINE_HISTORY_INDEX >= 0 )); then
        READLINE_LINE="$_RRSREADLINE_QUERY"
        READLINE_POINT=${#READLINE_LINE}
    fi
    if (( READLINE_POINT > 0 )); then
        READLINE_LINE="${READLINE_LINE:0:READLINE_POINT-1}${READLINE_LINE:READLINE_POINT}"
        READLINE_POINT=$(( READLINE_POINT - 1 ))
    fi
    __rrsreadline_update none
    _RRSREADLINE_BUSY=0
}

__rrsreadline_up() {
    _RRSREADLINE_BUSY=1
    __rrsreadline_update up
    _RRSREADLINE_BUSY=0
}

__rrsreadline_down() {
    _RRSREADLINE_BUSY=1
    __rrsreadline_update down
    _RRSREADLINE_BUSY=0
}

__rrsreadline_escape() {
    _RRSREADLINE_BUSY=1
    _RRSREADLINE_PREDICTIONS_HIDDEN=1
    _RRSREADLINE_QUERY=""
    _RRSREADLINE_SELECTED=-1
    _RRSREADLINE_SUGGESTIONS=()
    _RRSREADLINE_HISTORY_QUERY=""
    _RRSREADLINE_HISTORY_INDEX=-1
    __rrsreadline_clear
    _RRSREADLINE_BUSY=0
}

__rrsreadline_toggle_predictions() {
    _RRSREADLINE_BUSY=1
    if (( _RRSREADLINE_PREDICTIONS_HIDDEN )); then
        _RRSREADLINE_PREDICTIONS_HIDDEN=0
        __rrsreadline_update none 1
    else
        _RRSREADLINE_PREDICTIONS_HIDDEN=1
        _RRSREADLINE_SELECTED=-1
        __rrsreadline_clear
    fi
    _RRSREADLINE_BUSY=0
}

__rrsreadline_prompt_reset() {
    _RRSREADLINE_BUSY=0
    __rrsreadline_clear
    _RRSREADLINE_QUERY=""
    _RRSREADLINE_SELECTED=-1
    _RRSREADLINE_PREDICTIONS_HIDDEN=0
    _RRSREADLINE_SUGGESTIONS=()
    _RRSREADLINE_HISTORY_QUERY=""
    _RRSREADLINE_HISTORY_INDEX=-1
}

__rrsreadline_preexec() {
    [[ "$_RRSREADLINE_BUSY" == 1 ]] && return
    case "$BASH_COMMAND" in
        __rrsreadline_*) return ;;
    esac
    __rrsreadline_clear
}

bind 'set bind-tty-special-chars off'
bind 'set keyseq-timeout 50'
bind -x '"\e[12~": __rrsreadline_toggle_predictions'
"#;

fn static_bindings() -> &'static str {
    r#"bind -x '"\C-?": __rrsreadline_backspace'
bind -x '"\C-h": __rrsreadline_backspace'
bind -x '"\C-p": __rrsreadline_up'
bind -x '"\C-n": __rrsreadline_down'
bind -x '"\e": __rrsreadline_escape'
bind '"\e[A": "\C-p"'
bind '"\e[B": "\C-n"'
bind '"\eOA": "\C-p"'
bind '"\eOB": "\C-n"'

"#
}

fn character_bindings() -> String {
    let mut output = String::new();
    for byte in PRINTABLE_ASCII {
        let character = byte as char;
        let key = readline_keyseq_escape(character);
        let command = format!(
            "__rrsreadline_insert {}",
            shell_single_quote(&character.to_string())
        );
        let binding = format!("\"{key}\": {command}");
        output.push_str("bind -x ");
        output.push_str(&shell_single_quote(&binding));
        output.push('\n');
    }
    output.push('\n');
    output
}

fn shell_single_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

fn readline_keyseq_escape(character: char) -> String {
    match character {
        '\\' => "\\\\".to_owned(),
        '"' => "\\\"".to_owned(),
        other => other.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_script_contains_bash_handlers() {
        let script = generate(&Config::default());
        assert!(script.contains(r#"bind -x '"\C-p": __rrsreadline_up'"#));
        assert!(script.contains(r#"bind '"\e[A": "\C-p"'"#));
        assert!(script.contains("PROMPT_COMMAND="));
        assert!(script.contains("suggest --shell bash"));
        assert!(script.contains("_RRSREADLINE_PREDICTIONS_HIDDEN=0"));
        assert!(script.contains("__rrsreadline_toggle_predictions"));
    }

    #[test]
    fn generated_script_has_one_printable_binding_per_character() {
        let script = generate(&Config::default());
        assert_eq!(
            script
                .lines()
                .filter(
                    |line| line.starts_with("bind -x '") && line.contains("__rrsreadline_insert")
                )
                .count(),
            95
        );
    }

    #[test]
    fn generated_script_uses_configured_slot_count() {
        let config = Config {
            max_suggestions: 4,
            ..Config::default()
        };

        assert!(generate(&config).contains("_RRSREADLINE_SLOTS=4"));
    }
}
