//! Generates the Zsh integration evaluated from `.zshrc`.

use std::env;

/// Generates a self-contained Zsh integration script.
pub fn generate() -> String {
    let executable = env::current_exe()
        .ok()
        .and_then(|path| path.to_str().map(str::to_owned))
        .unwrap_or_else(|| "rrsreadline".to_owned());
    let executable = shell_single_quote(&executable);

    format!(
        r#"# Generated by `rrsreadline init zsh`.
# Reload `.zshrc` after changing the configuration.
typeset -g _RRSREADLINE_BIN={executable}
typeset -g _RRSREADLINE_QUERY=""
typeset -g _RRSREADLINE_SELECTED=-1
typeset -g _RRSREADLINE_PREDICTIONS_HIDDEN=0
typeset -ga _RRSREADLINE_SUGGESTIONS

_rrsreadline_refresh() {{
    emulate -L zsh
    local query=""
    (( CURSOR > 0 )) && query="${{BUFFER[1,CURSOR]}}"
    if [[ "$query" != "$_RRSREADLINE_QUERY" ]]; then
        _RRSREADLINE_QUERY="$query"
        _RRSREADLINE_SELECTED=-1
        _RRSREADLINE_PREDICTIONS_HIDDEN=0
    fi

    if (( _RRSREADLINE_PREDICTIONS_HIDDEN )); then
        _RRSREADLINE_SUGGESTIONS=()
        _RRSREADLINE_SELECTED=-1
        POSTDISPLAY=""
        return
    fi

    _RRSREADLINE_SUGGESTIONS=()
    if [[ -n "$query" ]]; then
        local output
        output="$($_RRSREADLINE_BIN suggest "$query")"
        if [[ -n "$output" ]]; then
            _RRSREADLINE_SUGGESTIONS=("${{(@f)output}}")
        fi
    fi

    if (( ${{#_RRSREADLINE_SUGGESTIONS}} == 0 )); then
        POSTDISPLAY=""
        _RRSREADLINE_SELECTED=-1
        return
    fi

    if (( _RRSREADLINE_SELECTED >= ${{#_RRSREADLINE_SUGGESTIONS}} )); then
        _RRSREADLINE_SELECTED=$(( ${{#_RRSREADLINE_SUGGESTIONS}} - 1 ))
    fi

    local i line=""
    for i in {{1..${{#_RRSREADLINE_SUGGESTIONS}}}}; do
        if (( i - 1 == _RRSREADLINE_SELECTED )); then
            line+="❯ ${{_RRSREADLINE_SUGGESTIONS[i]}}"
        else
            line+="  ${{_RRSREADLINE_SUGGESTIONS[i]}}"
        fi
        (( i < ${{#_RRSREADLINE_SUGGESTIONS}} )) && line+=$'\n'
    done
    POSTDISPLAY=$'\n'"$line"
}}

_rrsreadline_pre_redraw() {{
    _rrsreadline_refresh
}}

_rrsreadline_up() {{
    if (( _RRSREADLINE_PREDICTIONS_HIDDEN == 0 && ${{#_RRSREADLINE_SUGGESTIONS}} > 0 )); then
        if (( _RRSREADLINE_SELECTED < 0 )); then
            _RRSREADLINE_SELECTED=$(( ${{#_RRSREADLINE_SUGGESTIONS}} - 1 ))
        else
            _RRSREADLINE_SELECTED=$(( (_RRSREADLINE_SELECTED - 1 + ${{#_RRSREADLINE_SUGGESTIONS}}) % ${{#_RRSREADLINE_SUGGESTIONS}} ))
        fi
        zle redisplay
    else
        zle .up-line-or-history
        _RRSREADLINE_QUERY="${{BUFFER[1,CURSOR]}}"
        _RRSREADLINE_PREDICTIONS_HIDDEN=1
        zle redisplay
    fi
}}

_rrsreadline_down() {{
    if (( _RRSREADLINE_PREDICTIONS_HIDDEN == 0 && ${{#_RRSREADLINE_SUGGESTIONS}} > 0 )); then
        _RRSREADLINE_SELECTED=$(( (_RRSREADLINE_SELECTED + 1) % ${{#_RRSREADLINE_SUGGESTIONS}} ))
        zle redisplay
    else
        zle .down-line-or-history
        _RRSREADLINE_QUERY="${{BUFFER[1,CURSOR]}}"
        _RRSREADLINE_PREDICTIONS_HIDDEN=1
        zle redisplay
    fi
}}

_rrsreadline_accept() {{
    if (( _RRSREADLINE_SELECTED >= 0 && _RRSREADLINE_SELECTED < ${{#_RRSREADLINE_SUGGESTIONS}} )); then
        BUFFER="${{_RRSREADLINE_SUGGESTIONS[_RRSREADLINE_SELECTED + 1]}}"
        CURSOR=${{#BUFFER}}
        POSTDISPLAY=""
        _RRSREADLINE_SELECTED=-1
        zle redisplay
    else
        zle .accept-line
    fi
}}

_rrsreadline_tab() {{
    if (( _RRSREADLINE_SELECTED >= 0 && _RRSREADLINE_SELECTED < ${{#_RRSREADLINE_SUGGESTIONS}} )); then
        _rrsreadline_accept
    else
        zle _rrsreadline_native_expand_or_complete
    fi
}}

_rrsreadline_cancel() {{
    _RRSREADLINE_PREDICTIONS_HIDDEN=1
    POSTDISPLAY=""
    _RRSREADLINE_SELECTED=-1
    zle redisplay
}}

_rrsreadline_toggle_predictions() {{
    if (( _RRSREADLINE_PREDICTIONS_HIDDEN )); then
        _RRSREADLINE_PREDICTIONS_HIDDEN=0
    else
        _RRSREADLINE_PREDICTIONS_HIDDEN=1
        _RRSREADLINE_SELECTED=-1
    fi
    zle redisplay
}}

zle -N up-line-or-history _rrsreadline_up
zle -N down-line-or-history _rrsreadline_down
zle -N _rrsreadline_accept _rrsreadline_accept
zle -N _rrsreadline_tab _rrsreadline_tab
zle -A expand-or-complete _rrsreadline_native_expand_or_complete
zle -N accept-line _rrsreadline_accept
zle -N escape _rrsreadline_cancel
zle -N _rrsreadline_toggle_predictions _rrsreadline_toggle_predictions
zle -N zle-line-pre-redraw _rrsreadline_pre_redraw
bindkey '^[[A' up-line-or-history
bindkey '^[[B' down-line-or-history
bindkey '^M' accept-line
bindkey '^I' _rrsreadline_tab
bindkey '\e' escape
bindkey '^[[Z' reverse-menu-complete
bindkey '^[[12~' _rrsreadline_toggle_predictions
"#
    )
}

fn shell_single_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_script_contains_zle_hooks() {
        let script = generate();
        assert!(script.contains("zle -N zle-line-pre-redraw"));
        assert!(script.contains("zle -N up-line-or-history"));
        assert!(script.contains("zle -N _rrsreadline_tab _rrsreadline_tab"));
        assert!(script.contains("zle _rrsreadline_native_expand_or_complete"));
        assert!(
            script.contains("zle -A expand-or-complete _rrsreadline_native_expand_or_complete")
        );
        assert!(script.contains("bindkey '^I' _rrsreadline_tab"));
        assert!(script.contains("_RRSREADLINE_PREDICTIONS_HIDDEN=1"));
        assert!(script.contains("bindkey '^[[12~' _rrsreadline_toggle_predictions"));
        assert!(script.contains("suggest \"$query\""));
    }

    #[test]
    fn shell_quotes_single_quotes() {
        assert_eq!(shell_single_quote("a'b"), "'a'\\''b'");
    }
}
